### 
POST http://localhost:3000/auth/signup
Content-Type: application/json

{ 
  "userType" : "users",
  "name": "Jonayed Mohiuddin",
  "email": "jonayedmohiuddin@gmail.com",
  "password": "abc"
}

### 
POST http://localhost:3000/auth/login
Content-Type: application/json
 
{ 
  "userType": "users",
  "email": "jonayedmohiuddin@gmail.com",
  "password": "abc"
}

###
GET http://localhost:3000/cart/
 
###
POST http://localhost:3000/cart/add/
Content-Type: application/json

{
  "product_id": "3",
  "quantity": 1
}

###
POST http://localhost:3000/cart/update/
Content-Type: application/json

{
  "cart_item_id": "7",
  "quantity": 5
}

###
POST http://localhost:3000/cart/remove/
Content-Type: application/json

{
  "cart_item_id": "7"
}