###   
POST http://localhost:3000/auth/signup
Content-Type: application/json
 
{
  "userType": "supplier",
  "name": "Jim Doe",
  "email": "jonayedmohiuddin@gmail.com",
  "password": "abc"
}

### 
POST http://localhost:3000/auth/login
Content-Type: application/json
 
{ 
  "userType": "supplier",
  "email": "jonayedmohiuddin@gmail.com",
  "password": "abc"
}

###    
GET http://localhost:3000/supplier/all

### 
GET http://localhost:3000/supplier/products

###
POST http://localhost:3000/supplier/addProduct
Content-Type: application/json
 
{ 
  "categoryId": "1",
  "name": "Product 1",
  "price": 100,
  "description": "Product 1 description",
  "imageUrl": "images/no-product-image.jpg",
  "discount": 0.1
}

###
POST http://localhost:3000/supplier/updateProduct
Content-Type: application/json
 
{ 
  "productId": "1",
  "categoryId": "1",
  "name": "Product 1",
  "price": 100,
  "description": "hello",
  "imageUrl": "",
  "discount": 0.2
}

###
POST http://localhost:3000/supplier/removeProduct
Content-Type: application/json
 
{ 
  "productId": "2" 
}

###
POST http://localhost:3000/supplier/restoreProduct
Content-Type: application/json
 
{ 
  "productId": "2" 
}

###   
GET http://localhost:3000/supplier/orders

###  
GET http://localhost:3000/supplier/orders/PENDING

###
POST http://localhost:3000/supplier/orders/shipped/4

###
GET http://localhost:3000/supplier/about

### 
POST http://localhost:3000/supplier/update 
Content-Type: application/json
 
{ 
  "name": "Jonayed Mohiuddin",
  "email": "test@gmail.com",
  "address": "Dhaka, Bangladesh",
  "imageUrl": "images/no-profile-image.jpg",
  "description": "Hello, I am Jonayed Mohiuddin"
}

###
POST http://localhost:3000/supplier/remove

