###  
POST http://localhost:3000/auth/login
Content-Type: application/json
 
{ 
  "userType": "users",
  "email": "jonayedmohiuddin@gmail.com",
  "password": "abc"
} 

###   
POST http://localhost:3000/auth/signup
Content-Type: application/json
 
{
  "userType": "users",
  "name": "Jim Doe",
  "email": "jonayedmohiuddin@gmail.com",
  "password": "abc"
}

###
GET http://localhost:3000/users/orders

###
GET http://localhost:3000/users/orders/1

### 
POST http://localhost:3000/users/orders/add
Content-Type: application/json

{
    "productId": 1,
    "quantity": 5
}

###    
POST http://localhost:3000/users/orders/addFromCart

### 
POST http://localhost:3000/users/orders/cancel
Content-Type: application/json

{
    "orderItemId": 3
}

###
GET http://localhost:3000/users/reviews
 
###
POST http://localhost:3000/users/review/add 
Content-Type: application/json

{
    "productId": 1,
    "rating": 5,
    "review": "This is a good product"
}

###
POST http://localhost:3000/users/review/edit
Content-Type: application/json

{
    "productId": 1,
    "rating": 4,
    "review": "This is a good product"
}

###
POST http://localhost:3000/users/review/delete
Content-Type: application/json

{
    "productId": 1
}

###
GET http://localhost:3000/users/review/product/1

###
GET http://localhost:3000/users/orders/product/DELIVERED/1

### 
GET http://localhost:3000/users/wishlist

###
GET http://localhost:3000/users/wishlist/1

###
POST http://localhost:3000/users/wishlist/add
Content-Type: application/json

{
    "productId": 1
}

###
POST http://localhost:3000/users/wishlist/remove
Content-Type: application/json

{
    "productId": 1
}

### 
GET http://localhost:3000/users/about

### 
POST http://localhost:3000/users/update
Content-Type: application/json

{
    "name": "Jonayed Mohiuddin",
    "email": "jonayedmohiuddin@gmail.com",
    "phone": "01838380474",
    "address": "Dhaka, Bangladesh",
    "imageUrl": "test"
}

### 
POST http://localhost:3000/users/delete
