### 
POST http://localhost:3000/auth/login
Content-Type: application/json
 
{ 
  "userType": "users",
  "email": "jonayedmohiuddin@gmail.com",
  "password": "abc"
} 

###
GET http://localhost:3000/users/orders

###
GET http://localhost:3000/users/orders/1

###    
POST http://localhost:3000/users/orders/add
Content-Type: application/json

{
    "list" : [
        {
            "productId": 2,
            "quantity": 555
        },        
        {
            "productId": 1,
            "quantity": 255
        },  
        {
            "productId": 3,
            "quantity": 155
        }
    ]
}

### 
POST http://localhost:3000/users/orders/cancel
