### 
POST http://localhost:3000/auth/login
Content-Type: application/json
 
{ 
  "userType": "users",
  "email": "jonayedmohiuddin@gmail.com",
  "password": "abc"
} 

###
GET http://localhost:3000/users/orders

###
GET http://localhost:3000/users/orders/1

### 
POST http://localhost:3000/users/orders/add
Content-Type: application/json

{
    "productId": 1,
    "quantity": 5
}

###    
POST http://localhost:3000/users/orders/addFromCart

### 
POST http://localhost:3000/users/orders/cancel
Content-Type: application/json

{
    "orderItemId": 3
}
