INSERT INTO USERS(EMAIL, NAME, PASSWORD, IMAGE_URL) VALUES('jonayedmohiuddin@gmail.com', 'Jonayed Mohiuddin', HASH_PASSWORD('abc'), '/images/jonayed.jpg');
INSERT INTO USERS(EMAIL, NAME, PASSWORD, IMAGE_URL) VALUES('abdullah@gmail.com', 'Abdullah Jahed', HASH_PASSWORD('abc'), '/images/abdullah.jpg');
INSERT INTO USERS(EMAIL, NAME, PASSWORD) VALUES('janesmith@gmail.com', 'Jane Smith', HASH_PASSWORD('abc'));
INSERT INTO USERS(EMAIL, NAME, PASSWORD) VALUES('michaeljohnson@gmail.com', 'Michael Johnson', HASH_PASSWORD('abc'));
INSERT INTO USERS(EMAIL, NAME, PASSWORD) VALUES('emilydavis@gmail.com', 'Emily Davis', HASH_PASSWORD('abc'));
INSERT INTO USERS(EMAIL, NAME, PASSWORD) VALUES('robertwilson@gmail.com', 'Robert Wilson', HASH_PASSWORD('abc'));
INSERT INTO USERS(EMAIL, NAME, PASSWORD) VALUES('oliviabrown@yahoo.com', 'Olivia Brown', HASH_PASSWORD('abc'));
INSERT INTO USERS(EMAIL, NAME, PASSWORD) VALUES('williamtaylor@gmail.net', 'William Taylor', HASH_PASSWORD('abc'));
INSERT INTO USERS(EMAIL, NAME, PASSWORD) VALUES('sophiaanderson@gmail.org', 'Sophia Anderson', HASH_PASSWORD('abc'));
INSERT INTO USERS(EMAIL, NAME, PASSWORD) VALUES('jamesmartin@gmail.edu', 'James Martin', HASH_PASSWORD('abc'));

INSERT INTO ADMIN(NAME, PASSWORD, EMAIL) VALUES('ADMIN', HASH_PASSWORD('abc'), 'jonayedmohiuddin@gmail.com');

INSERT INTO SUPPLIER(NAME, PASSWORD, EMAIL) VALUES('TechGadget', HASH_PASSWORD('abc'), 'techgadget@gmail.com');
INSERT INTO SUPPLIER(NAME, PASSWORD, EMAIL) VALUES('StyleMart', HASH_PASSWORD('abc'), 'stylemart@gmail.com');
INSERT INTO SUPPLIER(NAME, PASSWORD, EMAIL) VALUES('EntertainmentHouse', HASH_PASSWORD('abc'), 'entertainmenthouse@gmail.com');
INSERT INTO SUPPLIER(NAME, PASSWORD, EMAIL) VALUES('AutoSportsDirect', HASH_PASSWORD('abc'), 'autosportsdirect@gmail.com');
INSERT INTO SUPPLIER(NAME, PASSWORD, EMAIL) VALUES('WellnessNaturals', HASH_PASSWORD('abc'), 'wellnessnaturals@gmail.com');
INSERT INTO SUPPLIER(NAME, PASSWORD, EMAIL) VALUES('DigitalOffice', HASH_PASSWORD('abc'), 'digitaloffice@gmail.com');

INSERT INTO CATEGORY(NAME, DESCRIPTION, IMAGE_URL) VALUES('Electronics', 'Explore the latest gadgets, computers, and home entertainment systems.', '/images/electronics.jpg');
INSERT INTO CATEGORY(NAME, DESCRIPTION, IMAGE_URL) VALUES('Fashion', 'Discover trendy clothing, accessories, and footwear for men, women, and kids.', '/images/fashion.jpg');
INSERT INTO CATEGORY(NAME, DESCRIPTION, IMAGE_URL) VALUES('Home & Garden', 'Find everything you need for your home, from furniture to decor and gardening tools.', '/images/garden.jpg');
INSERT INTO CATEGORY(NAME, DESCRIPTION, IMAGE_URL) VALUES('Sports & Outdoors', 'Gear up for your favorite sports and outdoor activities with our extensive collection.', '/images/sport.jpg');
INSERT INTO CATEGORY(NAME, DESCRIPTION, IMAGE_URL) VALUES('Personal Care', 'Pamper yourself with a wide range of skincare, makeup, and grooming products.', '/images/skincare.jpg');
INSERT INTO CATEGORY(NAME, DESCRIPTION, IMAGE_URL) VALUES('Books & Media', 'Explore a vast selection of books, movies, music, and more for your entertainment.', '/images/books.jpg');
INSERT INTO CATEGORY(NAME, DESCRIPTION, IMAGE_URL) VALUES('Toys & Games', 'Find fun and engaging toys, games, and puzzles for all ages.', '/images/games.jpg');
INSERT INTO CATEGORY(NAME, DESCRIPTION, IMAGE_URL) VALUES('Automotive', 'Shop for car parts, accessories, tools, and equipment for your vehicle.', '/images/automotive.jpg');
INSERT INTO CATEGORY(NAME, DESCRIPTION, IMAGE_URL) VALUES('Health & Wellness', 'Discover a wide range of products to support your physical and mental well-being.', '/images/health.jpg');
INSERT INTO CATEGORY(NAME, DESCRIPTION, IMAGE_URL) VALUES('Office Supplies', 'Stock up on essential stationery, office equipment, and educational materials.', '/images/office.jpg');

-- Electronics products from TechGadget Suppliers (Supplier ID: 1, Category ID: 1)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL, DISCOUNT) VALUES(1, 1, 'Smartphone', 799.99, '/images/phone.jpg', 0.1);
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(1, 1, 5, 'Great phone! I love the camera quality and battery life.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(1, 2, 4, 'Good phone, but a bit expensive.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(1, 3, 5, 'Excellent phone! I highly recommend it.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(1, 4, 5, 'I love the design and performance of this phone.');

INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL, DISCOUNT) VALUES(1, 1, 'Laptop', 1299.00, '/images/laptop.jpg', 0.15);
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(2, 1, 5, 'Great laptop! It is fast and has a long battery life.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(2, 2, 4, 'Good laptop, but a bit heavy.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(2, 3, 5, 'Excellent laptop! I highly recommend it.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(2, 4, 5, 'I love the design and performance of this laptop.');

INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL, DISCOUNT) VALUES(1, 1, 'Tablet', 499.99, '/images/tablet.jpg', 0.10);
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(3, 1, 5, 'Great tablet! It is fast and has a long battery life.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(3, 2, 4, 'Good tablet, but a bit heavy.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(3, 3, 5, 'Excellent tablet! I highly recommend it.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(3, 4, 5, 'I love the design and performance of this tablet.');

INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL) VALUES(1, 1, 'Smartwatch', 249.99, '/images/smartwatch.jpg');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(4, 1, 5, 'Great smartwatch! It is fast and has a long battery life.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(4, 2, 4, 'Good smartwatch, but a bit heavy.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(4, 3, 5, 'Excellent smartwatch! I highly recommend it.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(4, 4, 5, 'I love the design and performance of this smartwatch.');

INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL) VALUES(1, 1, 'Wireless Headphones', 99.99, '/images/headphones.jpg');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(5, 1, 5, 'Great headphones! They are comfortable and have good sound quality.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(5, 2, 4, 'Good headphones, but a bit expensive.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(5, 3, 5, 'Excellent headphones! I highly recommend them.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(5, 4, 5, 'I love the design and performance of these headphones.');

-- Home & Garden products from TechGadget Suppliers (Supplier ID: 1, Category ID: 3)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL) VALUES(1, 3, 'Robotic Vacuum Cleaner', 349.99, '/images/vacuum.jpg');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(6, 1, 5, 'Great vacuum! It is fast and has a long battery life.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(6, 2, 4, 'Good vacuum, but a bit heavy.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(6, 3, 5, 'Excellent vacuum! I highly recommend it.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(6, 4, 5, 'I love the design and performance of this vacuum.');

INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL) VALUES(1, 3, 'Smart Home Security System', 499.99, '/images/security.jpg');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(7, 1, 5, 'Great security system! It is fast and has a long battery life.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(7, 2, 4, 'Good security system, but a bit heavy.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(7, 3, 5, 'Excellent security system! I highly recommend it.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(7, 4, 5, 'I love the design and performance of this security system.');

-- Sports & Outdoors products from TechGadget Suppliers (Supplier ID: 1, Category ID: 4)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL) VALUES(1, 4, 'Action Camera', 249.99, '/images/camera.jpg');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(8, 1, 5, 'Great camera! It is fast and has a long battery life.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(8, 2, 4, 'Good camera, but a bit heavy.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(8, 3, 5, 'Excellent camera! I highly recommend it.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(8, 4, 5, 'I love the design and performance of this camera.');

-- INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 4, 'Fitness Tracker', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL) VALUES(1, 4, 'Fitness Tracker', 99.99, '/images/fitness.jpg');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(9, 1, 5, 'Great fitness tracker! It is fast and has a long battery life.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(9, 2, 4, 'Good fitness tracker, but a bit heavy.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(9, 3, 5, 'Excellent fitness tracker! I highly recommend it.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(9, 4, 5, 'I love the design and performance of this fitness tracker.');

-- Fashion products from StyleMart Suppliers (Supplier ID: 2, Category ID: 2)
-- INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 2, 'Dress', 49.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL) VALUES(2, 2, 'Dress', 49.99, '/images/dress.jpg');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(10, 1, 5, 'Great dress! It is fast and has a long battery life.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(10, 2, 4, 'Good dress, but a bit heavy.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(10, 3, 5, 'Excellent dress! I highly recommend it.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(10, 4, 5, 'I love the design and performance of this dress.');


-- INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 2, 'Jeans', 59.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL) VALUES(2, 2, 'Jeans', 59.99, '/images/jeans.jpg');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(11, 1, 5, 'Great jeans! It is fast and has a long battery life.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(11, 2, 4, 'Good jeans, but a bit heavy.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(11, 3, 5, 'Excellent jeans! I highly recommend it.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(11, 4, 5, 'I love the design and performance of these jeans.');

-- Personal Care products from StyleMart Suppliers (Supplier ID: 2, Category ID: 5)
-- INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 5, 'Skincare Set', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL) VALUES(2, 5, 'Skincare Set', 29.99, '/images/skincare.jpg');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(12, 1, 5, 'Great skincare set! It is fast and has a long battery life.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(12, 2, 4, 'Good skincare set, but a bit heavy.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(12, 3, 5, 'Excellent skincare set! I highly recommend it.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(12, 4, 5, 'I love the design and performance of this skincare set.');

-- INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 5, 'Makeup Palette', 24.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL) VALUES(2, 5, 'Makeup Palette', 24.99, '/images/skincare.jpg');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(13, 1, 5, 'Great makeup palette! It is fast and has a long battery life.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(13, 2, 4, 'Good makeup palette, but a bit heavy.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(13, 3, 5, 'Excellent makeup palette! I highly recommend it.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(13, 4, 5, 'I love the design and performance of this makeup palette.');

-- Electronics products from TechGadget Suppliers (Supplier ID: 1, Category ID: 1)
-- INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 1, 'Gaming Laptop', 1599.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL) VALUES(1, 1, 'Gaming Laptop', 1599.99, '/images/laptop.jpg');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(14, 5, 5, 'Great gaming laptop! It is fast and has a long battery life.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(14, 2, 4, 'Good gaming laptop, but a bit heavy.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(14, 3, 2, 'Excellent gaming laptop! I highly recommend it.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(14, 4, 5, 'I love the design and performance of this gaming laptop.');

-- INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 1, 'Wireless Headphones', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL) VALUES(1, 1, 'Wireless Headphones', 99.99, '/images/headphones.jpg');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(15, 5, 5, 'Great headphones! They are comfortable and have good sound quality.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(15, 2, 4, 'Good headphones, but a bit expensive.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(15, 3, 3, 'Excellent headphones! I highly recommend them.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(15, 4, 5, 'I love the design and performance of these headphones.');

-- INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 1, '4K Ultra HD TV', 799.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL) VALUES(1, 1, '4K Ultra HD TV', 799.99, '/images/tv.jpg');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(16, 5, 5, 'Great TV! It has a clear picture and good sound quality.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(16, 2, 4, 'Good TV, but a bit expensive.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(16, 3, 5, 'Excellent TV! I highly recommend it.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(16, 4, 1, 'I love the design and performance of this TV.');

-- INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 1, 'Smartwatch', 249.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL) VALUES(1, 1, 'Smartwatch', 249.99, '/images/smartwatch.jpg');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(17, 1, 5, 'Great smartwatch! It is fast and has a long battery life.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(17, 5, 4, 'Good smartwatch, but a bit heavy.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(17, 3, 5, 'Excellent smartwatch! I highly recommend it.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(17, 4, 5, 'I love the design and performance of this smartwatch.');

-- INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 1, 'Tablet', 349.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE, IMAGE_URL) VALUES(1, 1, 'Tablet', 349.99, '/images/tablet.jpg');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(18, 1, 4, 'Great tablet! It is fast and has a long battery life.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(18, 5, 1, 'Good tablet, but a bit heavy.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(18, 3, 3, 'Excellent tablet! I highly recommend it.');
INSERT INTO RATING_REVIEW (PRODUCT_ID, USER_ID, RATING, REVIEW) VALUES(18, 4, 5, 'I love the design and performance of this tablet.');

INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 1, 'Virtual Reality Headset', 399.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 1, 'Portable Speaker', 59.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 1, 'Wireless Router', 79.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 1, 'External Hard Drive', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 1, 'Printer', 149.99);

-- Home & Garden products from TechGadget Suppliers (Supplier ID: 1, Category ID: 3)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 3, 'Smart Home Security System', 499.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 3, 'Outdoor Smart Lighting', 149.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 3, 'Smart Sprinkler Controller', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 3, 'Indoor Garden Kit', 79.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 3, 'Smart Ceiling Fan', 199.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 3, 'Robotic Lawn Mower', 899.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 3, 'Smart Smoke Detector', 59.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 3, 'Smart Doorbell', 129.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 3, 'Outdoor Projector', 299.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 3, 'Smart Bed', 1499.99);

-- Sports & Outdoors products from TechGadget Suppliers (Supplier ID: 1, Category ID: 4)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 4, 'Drone', 499.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 4, 'GPS Watch', 199.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 4, 'Bluetooth Earbuds', 59.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 4, 'Portable Power Bank', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 4, 'Digital Binoculars', 149.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 4, 'Waterproof Camera', 299.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 4, 'Smart Tennis Sensor', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 4, 'Portable Projector', 249.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 4, 'Smart Bike Lock', 79.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 4, 'Gimbal Stabilizer', 149.99);

-- Fashion products from StyleMart Suppliers (Supplier ID: 2, Category ID: 2)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 2, 'Blouse', 34.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 2, 'Skirt', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 2, 'Suit', 199.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 2, 'Sweater', 49.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 2, 'Jacket', 79.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 2, 'Shorts', 24.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 2, 'Dress Shirt', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 2, 'Scarf', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 2, 'Belt', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 2, 'Tie', 12.99);

-- Personal Care products from StyleMart Suppliers (Supplier ID: 2, Category ID: 5)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 5, 'Facial Moisturizer', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 5, 'Shampoo', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 5, 'Perfume', 49.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 5, 'Razor', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 5, 'Body Lotion', 12.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 5, 'Makeup Remover', 7.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 5, 'Deodorant', 5.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 5, 'Lip Balm', 3.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 5, 'Facial Cleanser', 11.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 5, 'Toothpaste', 4.99);

-- Books & Media products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 6)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'Novel', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'Biography', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'Cookbook', 24.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'Blu-ray Movie', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'Audiobook', 12.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'Magazine Subscription', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'Music Album', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'E-book Reader', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'DVD Box Set', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'Educational Video Course', 49.99);

-- Toys & Games products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 7)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 7, 'Board Game', 24.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 7, 'Action Figure', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 7, 'Stuffed Animal', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 7, 'Lego Set', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 7, 'Puzzle', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 7, 'Remote Control Car', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 7, 'Doll', 12.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 7, 'Building Blocks', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 7, 'Trading Card Game', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 7, 'Art Supplies', 24.99);

-- Office Supplies products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 10)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Pen', 1.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Notebook', 4.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Printer Paper', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Binder', 6.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Sticky Notes', 2.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Desk Organizer', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'File Folders', 7.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Scissors', 3.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Highlighters', 2.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Stapler', 5.99);

-- Automotive products from AutoSportsDirect Suppliers (Supplier ID: 4, Category ID: 8)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Car Battery', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Tire', 89.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Brake Pads', 49.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Air Filter', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Wiper Blades', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Floor Mats', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Car Cover', 69.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Jump Starter', 59.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Car Vacuum', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Roof Rack', 149.99);

-- Sports & Outdoors products from AutoSportsDirect Suppliers (Supplier ID: 4, Category ID: 4)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 4, 'Camping Tent', 149.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 4, 'Hiking Backpack', 79.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 4, 'Fishing Rod', 49.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 4, 'Yoga Mat', 24.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 4, 'Baseball Bat', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 4, 'Basketball', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 4, 'Soccer Ball', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 4, 'Golf Club', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 4, 'Tennis Racket', 59.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 4, 'Bike Helmet', 29.99);

-- Health & Wellness products from WellnessNaturals Suppliers (Supplier ID: 5, Category ID: 9)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Vitamin C Supplement', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Protein Powder', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Multivitamin Tablets', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Fish Oil Capsules', 12.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Herbal Tea', 7.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Aloe Vera Gel', 11.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Essential Oil', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Probiotic Yogurt', 4.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Honey', 6.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Coconut Water', 3.99);

-- Electronics products from DigitalOffice Suppliers (Supplier ID: 6, Category ID: 1)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'Desktop Computer', 999.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'Computer Monitor', 199.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'Computer Keyboard', 49.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'Computer Mouse', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'Webcam', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'USB Flash Drive', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'Wireless Mouse', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'Laser Printer', 149.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'Computer Speakers', 59.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'External SSD', 99.99);

-- Home & Garden products from DigitalOffice Suppliers (Supplier ID: 6, Category ID: 3)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Door Lock', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Light Bulb', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Power Strip', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Window Blinds', 49.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Water Leak Sensor', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Garage Door Opener', 79.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Air Purifier', 149.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Humidifier', 59.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Water Filter', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Air Conditioner', 299.99);

-- Electronics products from DigitalOffice Suppliers (Supplier ID: 6, Category ID: 1)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'Wireless Keyboard', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'Wireless Router', 79.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'External Hard Drive', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'Printer', 149.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'Wireless Earbuds', 49.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'Wireless Charger', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'Wireless Speaker', 59.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'Wireless Headphones', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'Wireless Mouse', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 1, 'Wireless Security Camera', 149.99);

-- Home & Garden products from DigitalOffice Suppliers (Supplier ID: 6, Category ID: 3)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Doorbell', 129.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Thermostat', 199.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Smoke Detector', 59.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Sprinkler Controller', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Ceiling Fan', 199.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Home Security System', 499.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Outdoor Lighting', 149.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Indoor Garden', 79.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Robotic Vacuum', 349.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(6, 3, 'Smart Robotic Lawn Mower', 899.99);

-- Health & Wellness products from WellnessNaturals Suppliers (Supplier ID: 5, Category ID: 9)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Vitamin D Supplement', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Probiotic Supplement', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Omega-3 Supplement', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Calcium Supplement', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Magnesium Supplement', 7.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Iron Supplement', 11.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Zinc Supplement', 6.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Vitamin B12 Supplement', 12.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Vitamin E Supplement', 8.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(5, 9, 'Vitamin K Supplement', 10.99);

-- Automotive products from AutoSportsDirect Suppliers (Supplier ID: 4, Category ID: 8)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Motor Oil', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Car Wax', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Car Wash Soap', 7.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Car Polish', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Car Shampoo', 6.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Car Detailing Kit', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Car Tire Inflator', 24.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Car Polisher', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(4, 8, 'Car Scratch Remover', 19.99);

-- Books & Media products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 6)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'Novel', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'Biography', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'Cookbook', 24.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'Blu-ray Movie', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'Audiobook', 12.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'Magazine Subscription', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'Music Album', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'E-book Reader', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'DVD Box Set', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 6, 'Educational Video Course', 49.99);

-- Toys & Games products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 7)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 7, 'Board Game', 24.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 7, 'Action Figure', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 7, 'Stuffed Animal', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 7, 'Lego Set', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 7, 'Puzzle', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 7, 'Remote Control Car', 29.99);

-- Office Supplies products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 10)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Pen', 1.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Notebook', 4.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Printer Paper', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Binder', 6.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Sticky Notes', 2.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Desk Organizer', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'File Folders', 7.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Scissors', 3.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Highlighters', 2.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 10, 'Stapler', 5.99);

-- Electronics products from TechGadget Suppliers (Supplier ID: 1, Category ID: 1)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 1, 'Bluetooth Speaker', 59.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 1, 'E-book Reader', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 1, 'Wireless Earbuds', 49.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 1, 'Streaming Media Player', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 1, 'Digital Camera', 299.99);

-- Home & Garden products from TechGadget Suppliers (Supplier ID: 1, Category ID: 3)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 3, 'Smart Outlet', 24.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 3, 'Indoor Plant Monitor', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 3, 'Smart Irrigation System', 149.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 3, 'Outdoor Weather Station', 79.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 3, 'Smart Greenhouse', 399.99);

-- Sports & Outdoors products from TechGadget Suppliers (Supplier ID: 1, Category ID: 4)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 4, 'Smart Basketball', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 4, 'Golf Swing Analyzer', 149.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 4, 'Fitness Tracker Watch', 129.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 4, 'Cycling Computer', 89.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 4, 'Outdoor Smart Watch', 199.99);

-- Fashion products from StyleMart Suppliers (Supplier ID: 2, Category ID: 2)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 2, 'Sandals', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 2, 'Sunglasses', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 2, 'Handbag', 49.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 2, 'Wallet', 24.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 2, 'Jewelry Set', 39.99);

-- Personal Care products from StyleMart Suppliers (Supplier ID: 2, Category ID: 5)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 5, 'Hair Conditioner', 7.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 5, 'Beard Oil', 12.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 5, 'Foot Cream', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 5, 'Bath Salts', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 5, 'Teeth Whitening Kit', 24.99);

-- Books & Media products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 6)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Poetry Book', 11.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Comic Book', 6.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Art Book', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Travel Guide', 16.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Photography Magazine', 9.99);

-- Toys & Games products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 7)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Playing Cards', 4.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Frisbee', 7.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Kite', 12.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Yo-yo', 5.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Magic Trick Set', 19.99);

-- Office Supplies products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 10)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Ruler', 1.49);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Paper Clips', 0.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Rubber Bands', 1.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Tape Dispenser', 6.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Hole Punch', 3.99);

-- Automotive products from AutoSportsDirect Suppliers (Supplier ID: 4, Category ID: 8)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 8, 'Windshield Wiper Fluid', 4.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 8, 'Antifreeze', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 8, 'Headlight Bulb', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 8, 'Spark Plugs', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 8, 'Fuel Injector Cleaner', 7.99);

-- Sports & Outdoors products from AutoSportsDirect Suppliers (Supplier ID: 4, Category ID: 4)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 4, 'Kayak', 399.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 4, 'Surfboard', 299.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 4, 'Skateboard', 69.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 4, 'Punching Bag', 79.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 4, 'Resistance Bands', 24.99);

-- Health & Wellness products from WellnessNaturals Suppliers (Supplier ID: 5, Category ID: 9)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (5, 9, 'Green Tea Extract', 11.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (5, 9, 'Turmeric Supplement', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (5, 9, 'Ginger Supplement', 12.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (5, 9, 'Garlic Supplement', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (5, 9, 'Glucosamine Supplement', 19.99);

-- Electronics products from DigitalOffice Suppliers (Supplier ID: 6, Category ID: 1)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 1, 'Portable Projector', 149.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 1, 'Smartpen', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 1, '3D Printer', 299.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 1, 'Tablet Stand', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 1, 'Laptop Cooling Pad', 24.99);

-- Home & Garden products from DigitalOffice Suppliers (Supplier ID: 6, Category ID: 3)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 3, 'Smart Pet Feeder', 79.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 3, 'Smart Plant Pot', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 3, 'Smart Irrigation Controller', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 3, 'Smart Weather Station', 149.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 3, 'Smart Outdoor Camera', 99.99);

-- Books & Media products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 6)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Children''s Book', 7.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Graphic Novel', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Self-Help Book', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Science Fiction Novel', 12.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Music Vinyl Record', 24.99);

-- Toys & Games products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 7)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Chess Set', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Ring Toss Game', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Juggling Balls', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Hula Hoop', 11.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Dart Board', 39.99);

-- Office Supplies products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 10)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Paper Clips', 0.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Rubber Bands', 1.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Tape Dispenser', 6.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Hole Punch', 3.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Pencil Sharpener', 2.99);

-- Electronics products from TechGadget Suppliers (Supplier ID: 1, Category ID: 1)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 1, 'DSLR Camera', 799.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 1, 'Mirrorless Camera', 599.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 1, 'Action Camera', 199.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 1, 'Compact Camera', 149.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 1, 'Camera Lens', 299.99);

-- Home & Garden products from TechGadget Suppliers (Supplier ID: 1, Category ID: 3)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 3, 'Smart Grill', 399.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 3, 'Smart Oven', 799.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 3, 'Smart Refrigerator', 1499.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 3, 'Smart Dishwasher', 999.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 3, 'Smart Washing Machine', 1199.99);

-- Sports & Outdoors products from TechGadget Suppliers (Supplier ID: 1, Category ID: 4)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 4, 'Smart Baseball', 49.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 4, 'Smart Hockey Puck', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 4, 'Smart Tennis Racket', 199.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 4, 'Smart Ski Goggles', 299.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (1, 4, 'Smart Fishing Rod', 149.99);

-- Fashion products from StyleMart Suppliers (Supplier ID: 2, Category ID: 2)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 2, 'Evening Gown', 199.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 2, 'Tuxedo', 499.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 2, 'Cocktail Dress', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 2, 'Blazer', 149.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 2, 'Trousers', 79.99);

-- Personal Care products from StyleMart Suppliers (Supplier ID: 2, Category ID: 5)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 5, 'Hair Serum', 16.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 5, 'Face Mask', 24.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 5, 'Body Scrub', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 5, 'Hand Cream', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (2, 5, 'Eye Cream', 29.99);

-- Books & Media products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 6)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Historical Fiction Novel', 16.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Mystery Novel', 12.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Romance Novel', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Thriller Novel', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Fantasy Novel', 17.99);

-- Toys & Games products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 7)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Jigsaw Puzzle', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Rubiks Cube', 9.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Slinky', 5.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Kendama', 14.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Hacky Sack', 7.99);

-- Office Supplies products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 10)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Pencil Case', 6.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Correction Tape', 2.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Drawing Compass', 4.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Glue Stick', 1.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Whiteboard Markers', 5.99);

-- Automotive products from AutoSportsDirect Suppliers (Supplier ID: 4, Category ID: 8)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 8, 'Brake Rotor', 69.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 8, 'Brake Caliper', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 8, 'Spark Plug Wire Set', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 8, 'Fuel Filter', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 8, 'Cabin Air Filter', 14.99);

-- Sports & Outdoors products from AutoSportsDirect Suppliers (Supplier ID: 4, Category ID: 4)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 4, 'Snowboard', 349.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 4, 'Ski Set', 499.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 4, 'Climbing Gear', 199.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 4, 'Archery Set', 149.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 4, 'Boxing Gloves', 59.99);

-- Health & Wellness products from WellnessNaturals Suppliers (Supplier ID: 5, Category ID: 9)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (5, 9, 'Whey Protein', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (5, 9, 'Plant-Based Protein', 24.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (5, 9, 'Weight Loss Supplement', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (5, 9, 'Joint Support Supplement', 21.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (5, 9, 'Melatonin Supplement', 9.99);

-- Electronics products from DigitalOffice Suppliers (Supplier ID: 6, Category ID: 1)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 1, 'Gaming Headset', 79.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 1, 'Graphics Tablet', 149.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 1, 'Portable Scanner', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 1, 'Wireless Printer', 199.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 1, 'Laptop Sleeve', 29.99);

-- Home & Garden products from DigitalOffice Suppliers (Supplier ID: 6, Category ID: 3)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 3, 'Smart Outdoor Grill', 499.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 3, 'Smart Outdoor TV', 1499.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 3, 'Smart Landscape Lighting', 299.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 3, 'Smart Outdoor Speaker', 199.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (6, 3, 'Smart Garden Planter', 79.99);

-- Books & Media products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 6)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Graphic Design Book', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Photography Book', 24.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Art Instruction Book', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Screenplay Book', 16.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 6, 'Coloring Book', 8.99);

-- Toys & Games products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 7)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Foosball Table', 199.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Ping Pong Table', 249.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Inflatable Bounce House', 399.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Laser Tag Set', 99.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 7, 'Playhouse', 149.99);

-- Office Supplies products from EntertainmentHouse Suppliers (Supplier ID: 3, Category ID: 10)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Paper Trimmer', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Label Maker', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Laminating Machine', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Shredder', 49.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (3, 10, 'Binding Machine', 59.99);

-- Automotive products from AutoSportsDirect Suppliers (Supplier ID: 4, Category ID: 8)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 8, 'Car Ramp', 79.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 8, 'Car Jack', 39.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 8, 'Wheel Chocks', 19.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 8, 'Emergency Road Kit', 29.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 8, 'Car Roof Rack', 149.99);

-- Sports & Outdoors products from AutoSportsDirect Suppliers (Supplier ID: 4, Category ID: 4)
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 4, 'Treadmill', 999.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 4, 'Elliptical Machine', 799.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 4, 'Exercise Bike', 499.99);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES (4, 4, 'Weight Bench', 249.99);

INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (2, 2, 4, 'Great laptop with good performance, but battery life could be better.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (3, 3, 5, 'Excellent smart TV with amazing picture quality and user-friendly interface.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (4, 4, 3, 'The vacuum cleaner works well on hardwood floors but struggles with high-pile carpets.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (5, 5, 4, 'Easy to set up and use, helps save energy and reduces utility bills.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 6, 5, 'Captures amazing video quality, perfect for outdoor adventures.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (7, 7, 3, 'Decent fitness tracker but lacks some advanced features found in higher-end models.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (8, 8, 4, 'Stylish and comfortable dress, great for casual or semi-formal occasions.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (9, 9, 5, 'Well-made jeans that fit perfectly and retain their shape after multiple washes.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (10, 10, 4, 'Good value for money, but the products have a slightly artificial scent.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (1, 11, 3, 'Decent makeup palette with a good selection of shades, but some colors lack pigmentation.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (2, 12, 5, 'Powerful gaming laptop with impressive graphics and smooth performance.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (3, 13, 4, 'Great sound quality and comfortable fit, but battery life could be better.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (4, 14, 5, 'Stunning 4K picture quality with vibrant colors and deep blacks.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (5, 15, 3, 'Basic smartwatch with limited features, but good for tracking fitness activities.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 16, 4, 'Fast and responsive tablet with a decent battery life, but lacks expandable storage.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (7, 17, 5, 'Immersive VR experience with excellent motion tracking and comfortable headset design.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (8, 18, 4, 'Good sound quality for its size and price, but lacks bass and depth.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (9, 19, 3, 'Reliable router with decent range, but setup process could be simpler.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (10, 20, 5, 'Ample storage capacity and fast transfer speeds, perfect for backup and file storage.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (1, 21, 4, 'Good all-in-one printer for home or small office use, but ink cartridges are expensive.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (2, 22, 5, 'Comprehensive security system with easy-to-use app and reliable monitoring.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (3, 23, 4, 'Adds a nice ambiance to outdoor spaces, but installation can be tricky.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (4, 24, 3, 'Works as intended, but could use more scheduling and zone control options.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (5, 25, 5, 'Perfect for growing herbs and small plants indoors with minimal maintenance.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 26, 4, 'Sleek and quiet ceiling fan with useful smart features, but remote could be more responsive.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (7, 27, 3, 'Efficient lawn mower, but requires careful setup and boundary wire installation.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (8, 28, 5, 'Reliable smoke detector with easy installation and maintenance.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (9, 29, 4, 'Clear video and two-way audio, but motion detection could be more sensitive.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (10, 30, 3, 'Good picture quality, but limited connectivity options and mediocre built-in speakers.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (1, 31, 5, 'Innovative and comprehensive smart bed with useful features for better sleep.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (2, 32, 4, 'Easy to fly and captures smooth aerial footage, but battery life is limited.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (3, 33, 5, 'Accurate GPS tracking and useful fitness metrics for outdoor activities.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (4, 34, 3, 'Decent sound quality, but ear tips could be more comfortable for extended use.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (5, 35, 4, 'Compact and reliable power bank, but charging speed could be faster.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 36, 5, 'Impressive image quality and long-range viewing, perfect for outdoor enthusiasts.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (7, 37, 4, 'Waterproof design and rugged construction, but menu system could be more user-friendly.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (8, 38, 3, 'Provides useful data, but could be more accurate and consistent in tracking.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (9, 39, 5, 'Bright and clear image, perfect for outdoor movie nights or presentations.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (10, 40, 4, 'Secure and easy to use, but could benefit from additional smart features.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (1, 41, 3, 'Keeps the camera steady, but setup and balancing can be tricky.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (2, 42, 5, 'Stylish and versatile blouse that can be dressed up or down.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (3, 43, 4, 'Flattering skirt with a comfortable fit, but runs slightly small.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (4, 44, 3, 'Well-tailored suit, but the fabric could be of better quality.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (5, 45, 5, 'Cozy and warm sweater, perfect for layering during colder months.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 46, 4, 'Stylish jacket with a flattering fit, but lacks insulation for cold weather.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (7, 47, 3, 'Comfortable shorts, but the material feels a bit thin and lacks stretch.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (8, 48, 5, 'Well-made dress shirt with a crisp look and comfortable fabric.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (9, 49, 4, 'Soft and versatile scarf, but the material can be prone to shedding.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (10, 50, 3, 'Decent belt for the price, but the buckle feels a bit flimsy.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (1, 51, 5, 'Classic tie with a timeless design and durable construction.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (2, 52, 4, 'Hydrating moisturizer with a pleasant scent and non-greasy feel.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (3, 53, 3, 'Cleanses hair well, but the scent is a bit strong for sensitive users.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (4, 54, 5, 'Long-lasting fragrance with a unique and pleasant scent.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (5, 55, 4, 'Sharp and precise razor, but the handle could be more ergonomic.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 56, 3, 'Moisturizes skin well, but the scent is a bit strong for sensitive users.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (7, 57, 5, 'Effective deodorant with a pleasant scent and long-lasting protection.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (8, 58, 4, 'Moisturizes lips well, but the scent is a bit strong for sensitive users.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (9, 59, 3, 'Cleanses skin well, but the scent is a bit strong for sensitive users.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (10, 60, 5, 'Freshens breath and cleans teeth well, perfect for daily use.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (1, 61, 4, 'Cleanses skin well, but the scent is a bit strong for sensitive users.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (2, 62, 5, 'Engaging and well-written novel with memorable characters and plot.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (3, 63, 4, 'Informative and inspiring biography with valuable life lessons.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (4, 64, 3, 'Useful cookbook with a good variety of recipes, but some lack detail.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (5, 65, 5, 'Entertaining and visually stunning movie with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 66, 4, 'Engaging and well-narrated audiobook with a captivating story.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (7, 67, 3, 'Informative and well-written magazine with a good variety of articles.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (8, 68, 5, 'Captivating and well-acted play with a thought-provoking storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (9, 69, 4, 'Entertaining and visually stunning video game with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (10, 70, 3, 'Engaging and well-written novel with memorable characters and plot.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (1, 71, 5, 'Informative and inspiring biography with valuable life lessons.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (2, 72, 4, 'Useful cookbook with a good variety of recipes, but some lack detail.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (3, 73, 3, 'Entertaining and visually stunning movie with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (4, 74, 5, 'Engaging and well-narrated audiobook with a captivating story.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (5, 75, 4, 'Informative and well-written magazine with a good variety of articles.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 76, 3, 'Captivating and well-acted play with a thought-provoking storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (7, 77, 5, 'Entertaining and visually stunning video game with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (8, 78, 4, 'Engaging and well-written novel with memorable characters and plot.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (9, 79, 3, 'Informative and inspiring biography with valuable life lessons.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (10, 80, 5, 'Useful cookbook with a good variety of recipes, but some lack detail.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (1, 81, 4, 'Entertaining and visually stunning movie with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (2, 82, 3, 'Engaging and well-narrated audiobook with a captivating story.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (3, 83, 5, 'Informative and well-written magazine with a good variety of articles.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (4, 84, 4, 'Captivating and well-acted play with a thought-provoking storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (5, 85, 3, 'Entertaining and visually stunning video game with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 86, 5, 'Engaging and well-written novel with memorable characters and plot.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (7, 87, 4, 'Informative and inspiring biography with valuable life lessons.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (8, 88, 3, 'Useful cookbook with a good variety of recipes, but some lack detail.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (9, 89, 5, 'Entertaining and visually stunning movie with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (10, 90, 4, 'Engaging and well-narrated audiobook with a captivating story.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (1, 91, 3, 'Informative and well-written magazine with a good variety of articles.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (2, 92, 5, 'Captivating and well-acted play with a thought-provoking storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (3, 93, 4, 'Entertaining and visually stunning video game with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (4, 94, 3, 'Engaging and well-written novel with memorable characters and plot.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (5, 95, 5, 'Informative and inspiring biography with valuable life lessons.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 96, 4, 'Useful cookbook with a good variety of recipes, but some lack detail.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (7, 97, 3, 'Entertaining and visually stunning movie with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (8, 98, 5, 'Engaging and well-narrated audiobook with a captivating story.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (9, 99, 4, 'Informative and well-written magazine with a good variety of articles.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (10, 100, 3, 'Captivating and well-acted play with a thought-provoking storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (1, 101, 5, 'Entertaining and visually stunning video game with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (2, 102, 4, 'Engaging and well-written novel with memorable characters and plot.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (3, 103, 3, 'Informative and inspiring biography with valuable life lessons.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (4, 104, 5, 'Useful cookbook with a good variety of recipes, but some lack detail.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (5, 105, 4, 'Entertaining and visually stunning movie with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 106, 3, 'Engaging and well-narrated audiobook with a captivating story.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (7, 107, 5, 'Informative and well-written magazine with a good variety of articles.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (8, 108, 4, 'Captivating and well-acted play with a thought-provoking storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (9, 109, 3, 'Entertaining and visually stunning video game with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (10, 110, 5, 'Engaging and well-written novel with memorable characters and plot.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (1, 111, 4, 'Informative and inspiring biography with valuable life lessons.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (2, 112, 3, 'Useful cookbook with a good variety of recipes, but some lack detail.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (3, 113, 5, 'Entertaining and visually stunning movie with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (4, 114, 4, 'Engaging and well-narrated audiobook with a captivating story.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (5, 115, 3, 'Informative and well-written magazine with a good variety of articles.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 116, 5, 'Captivating and well-acted play with a thought-provoking storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (7, 117, 4, 'Entertaining and visually stunning video game with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (8, 118, 3, 'Engaging and well-written novel with memorable characters and plot.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (9, 119, 5, 'Informative and inspiring biography with valuable life lessons.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (10, 120, 4, 'Useful cookbook with a good variety of recipes, but some lack detail.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (1, 121, 3, 'Entertaining and visually stunning movie with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (2, 122, 5, 'Engaging and well-narrated audiobook with a captivating story.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (3, 123, 4, 'Informative and well-written magazine with a good variety of articles.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (4, 124, 3, 'Captivating and well-acted play with a thought-provoking storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (5, 125, 5, 'Entertaining and visually stunning video game with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 126, 4, 'Engaging and well-written novel with memorable characters and plot.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (7, 127, 3, 'Informative and inspiring biography with valuable life lessons.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (8, 128, 5, 'Useful cookbook with a good variety of recipes, but some lack detail.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (9, 129, 4, 'Entertaining and visually stunning movie with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (10, 130, 3, 'Engaging and well-narrated audiobook with a captivating story.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (1, 131, 5, 'Informative and well-written magazine with a good variety of articles.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (2, 132, 4, 'Captivating and well-acted play with a thought-provoking storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (3, 133, 3, 'Entertaining and visually stunning video game with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (4, 134, 5, 'Engaging and well-written novel with memorable characters and plot.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (5, 135, 4, 'Informative and inspiring biography with valuable life lessons.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 136, 3, 'Useful cookbook with a good variety of recipes, but some lack detail.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (7, 137, 5, 'Entertaining and visually stunning movie with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (8, 138, 4, 'Engaging and well-narrated audiobook with a captivating story.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (9, 139, 3, 'Informative and well-written magazine with a good variety of articles.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (10, 140, 5, 'Captivating and well-acted play with a thought-provoking storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (1, 141, 4, 'Entertaining and visually stunning video game with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (2, 142, 3, 'Engaging and well-written novel with memorable characters and plot.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (3, 143, 5, 'Informative and inspiring biography with valuable life lessons.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (4, 144, 4, 'Useful cookbook with a good variety of recipes, but some lack detail.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (5, 145, 3, 'Entertaining and visually stunning movie with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 146, 5, 'Engaging and well-narrated audiobook with a captivating story.');

INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 1, 5, 'Engaging and well-narrated audiobook with a captivating story.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 2, 4, 'Informative and inspiring biography with valuable life lessons.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 3, 3, 'Useful cookbook with a good variety of recipes, but some lack detail.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 4, 5, 'Entertaining and visually stunning movie with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 5, 4, 'Engaging and well-narrated audiobook with a captivating story.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 6, 3, 'Informative and inspiring biography with valuable life lessons.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 7, 5, 'Useful cookbook with a good variety of recipes, but some lack detail.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 8, 4, 'Entertaining and visually stunning movie with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 9, 3, 'Engaging and well-narrated audiobook with a captivating story.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 10, 5, 'Informative and inspiring biography with valuable life lessons.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 11, 4, 'Useful cookbook with a good variety of recipes, but some lack detail.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 12, 3, 'Entertaining and visually stunning movie with a compelling storyline.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 13, 5, 'Engaging and well-narrated audiobook with a captivating story.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 14, 4, 'Informative and inspiring biography with valuable life lessons.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 15, 3, 'Useful cookbook with a good variety of recipes, but some lack detail.');
INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 16, 5, 'Entertaining and visually stunning movie with a compelling storyline.');

INSERT INTO RATING_REVIEW (USER_ID, PRODUCT_ID, RATING, REVIEW) VALUES (6, 1, 4, 'Engaging and well-narrated audiobook with a captivating story.');