CREATE OR REPLACE TRIGGER USERS_BEFORE_INSERT
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    :NEW.CREATED_ON := SYSDATE;
    :NEW.LAST_UPDATED_ON := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER USERS_BEFORE_UPDATE
BEFORE UPDATE ON USERS
FOR EACH ROW
BEGIN
    :NEW.LAST_UPDATED_ON := SYSDATE;
END;
/