INSERT INTO USERS(EMAIL, NAME, PASSWORD) VALUES('jonayedmohiuddin@gmail.com', 'Jonayed Mohiuddin', HASH_PASSWORD('abc'));

INSERT INTO SUPPLIER(NAME, PASSWORD, EMAIL) VALUES('ELECTRONICS MART', HASH_PASSWORD('abc'), 'TEST3@gmail.com');
INSERT INTO SUPPLIER(NAME, PASSWORD, EMAIL) VALUES('FASHION MART', HASH_PASSWORD('abc'), 'TEST2@gmail.com');
INSERT INTO SUPPLIER(NAME, PASSWORD, EMAIL) VALUES('LOGIC GATES', HASH_PASSWORD('abc'), 'TEST1@gmail.com');


INSERT INTO CATEGORY(NAME) VALUES('CAT1');
INSERT INTO CATEGORY(NAME) VALUES('CAT2');
INSERT INTO CATEGORY(NAME) VALUES('CAT3');

INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 1, 'Bulb', 219);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 2, 'Fan', 999);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 3, 'Iron', 499);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(1, 1, 'Heater', 1999);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 2, 'Kettle', 799);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 3, 'Toaster', 499);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 1, 'Cooker', 2999);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 2, 'Mixer', 999);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 3, 'Blender', 499);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 1, 'Juicer', 1999);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 2, 'Grinder', 799);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(2, 3, 'Chopper', 499);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 1, 'Shaver', 2999);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 2, 'Trimmer', 999);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 3, 'Hair Dryer', 499);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 1, 'Hair Straightener', 1999);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 2, 'Hair Curler', 799);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 3, 'Hair Crimper', 499);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 1, 'Hair Roller', 2999);
INSERT INTO PRODUCT (SUPPLIER_ID, CATEGORY_ID, NAME, PRICE) VALUES(3, 2, 'Hair Waver', 999);

INSERT INTO ORDERS(USER_ID, PHONE_1, ADDRESS) VALUES(1, '1234567890', 'Kathmandu');
INSERT INTO ORDER_ITEM(ORDER_ID, PRODUCT_ID, QUANTITY, STATUS) VALUES(1, 1, 2, 'Processing');
INSERT INTO ORDER_ITEM(ORDER_ID, PRODUCT_ID, QUANTITY, STATUS) VALUES(1, 2, 6, 'Processing');
INSERT INTO ORDER_ITEM(ORDER_ID, PRODUCT_ID, QUANTITY, STATUS) VALUES(1, 3, 23, 'Processing');
INSERT INTO ORDER_ITEM(ORDER_ID, PRODUCT_ID, QUANTITY, STATUS) VALUES(1, 4, 7, 'Processing');

